### ISSUE TITLE
Occurs timer is missing when closing app.

### ISSUE THREAD

**Issue by rageworx** [redg25/GIA_practice#4]
Hello there,
I am preparing GIA test, and used your repo to practice.
But there's something strange questions, and no results - maybe not implemented it ?
Anyway, I'd check an error found when close app on macOS iterm2 through python log here
```
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/Users/raphaelkim/Projects/GIA/GIA_practice/game_gia.py", line 395, in <module>
     app.run()
   File "/usr/local/lib/python3.11/site-packages/kivy/app.py", line 957, in run
     self._stop()
   File "/usr/local/lib/python3.11/site-packages/kivy/app.py", line 985, in _stop
     self.dispatch('on_stop')
   File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/Users/raphaelkim/Projects/GIA/GIA_practice/game_gia.py", line 390, in on_stop
     if self.root.current_screen.timer is not None:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'Menu' object has no attribute 'timer'
```
and here's my pip list to debug.
```
> pip list
Package               Version
--------------------- --------
blinker               1.6.2
certifi               2023.5.7
charset-normalizer    3.1.0
click                 8.1.3
distlib               0.3.6
docutils              0.20.1
filelock              3.12.2
Flask                 2.3.2
fpdf                  1.7.2
idna                  3.4
itsdangerous          2.1.2
Jinja2                3.1.2
Kivy                  2.2.1
Kivy-Garden           0.1.5
MarkupSafe            2.1.3
numpy                 1.25.0
Pillow                10.0.0
pip                   23.1.2
platformdirs          3.8.0
protobuf              4.23.3
pycairo               1.24.0
Pygments              2.15.1
PyGObject             3.44.1
PyQt3D                5.15.5
PyQt5                 5.15.7
PyQt5-sip             12.11.0
PyQtChart             5.15.6
PyQtDataVisualization 5.15.5
PyQtNetworkAuth       5.15.5
PyQtPurchasing        5.15.5
PyQtWebEngine         5.15.6
requests              2.31.0
setuptools            67.6.1
six                   1.16.0
TBB                   0.2
timer                 0.2.2
urllib3               2.0.3
virtualenv            20.23.1
Werkzeug              2.3.6
wheel                 0.40.0
```
Hope it could help make it better result.
Regards, Raph.

**Comment by redg25** [comment]
@ColmBhandal What is the point of

```
 def on_stop(self):
    if self.root.current_screen.timer is not None:
        self.root.current_screen.timer.cancel()
```
It closes the whole app, so why do you want to reset the timer? It creates an error when closing on the menu screen because it doesn't have a timer attribute. I am happy to leave it and update the code to prevent the error but if it is unnecessary, we could as well remove it
@rageworx I am glad to hear you are using it for practise, I had the idea 2 years ago when I noticed that there wasn't any free training platform while the algorythms are fairly simple to reproduce.

**Comment by redg25** [comment]
@rageworx Do you have examples of 'strange questions' and 'no results'?

**Comment by rageworx** [comment]
> @rageworx Do you have examples of 'strange questions' and 'no results'?

Sorry to fix my answer.

My question is, 
No result screen when I had any test.
I just wanted to know is there test result screen may displayed, because it isn't displayed anything to me.
So I thought it was strange, as a bug if don't show result page only for me.

I am not well in Python.
Just I followed Kivy installation web page, and tried to run your app.
And displayed menu has not timer attribute for latest python.
Maybe it is a reason of Python library version dependency ?
I'm not sure.

Best regards, Raph.
